<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Laboratorio extends Model
{
    use HasFactory;
    protected $table = 'laboratorio';
    protected $fillable = [

        'paciente_idL',
          'fechaLa',
          'edad',
          'solicitado',
          'biometria',
          'hematocrito',
          'contaje',
          'velocidad',
          'reticulocitos',
          'hematozoario',
          'grupo',
          'coombsD',
          'ComombsI',
          'tp',
          'ttp',
          'tiempoH',
          'tiempoC',
          'glucosa',
          'curva',
          'curvaTole', 
          'hemoglobina',
          'urea',
          'bun',
          'creatinina',
          'acido',
          'colesterol',
          'trigliceridos',
          'hdl',
          'lipidos',
          'proteinas',
          'albumina',
          'globulina',
          'bilirubinas',
          'tgo',
          'tgp',
          'fosfatasa',
          'gamma',
          'ldh',
          'amilasa', 
          'lipasa',
          'cpk',
          'ck',
          'troponina',
          'sodio',
          'calcio',
          'calcioI',
          'fosfato',
          'magnesio',
          'asto',
          'fr',
          'pcr',
          'aglutinaciones',
          'vdrl',
          'hiv',
          'toxoplasma',
          'toxoplasmalg',
          'toxoplasmalm',
          'rubeola',
          'rubeolalg',
          'rubeolalm',
          'citomegalovirus',
          'citomegaloviruslg',
          'citomegaloviruslm',
          'herpes1',
          'herpes1lg',
          'herpes1lm',
          'herpes2',
          'herpes2lg',
          'herpes2lm',
          'hepatitisA',
          'hepatitisAlm',
          'hepatitisB',
          'hepatitisC',
          'helicobacter',
          'mononucleosis',
          't3',
          't3L',
          't4T',
          't4L',
          'tsh',
          'testE',
          'hcg',
          'fsh',
          'lh',
          'prolactina',
          'estrogenos',
          'progesterona',
          'testoterona',
          'insulina',
          'ana',
          'dna',
          'antifosfolípidos',
          'antifosfolípidosLG',
          'antifosfolípidosLM',
          'tpo',
          'Atiroglobulina',
          'antiCoagulante',
          'ccp',
          'afp',
          'cea',
          'psa',
          'psaL',
          'ca',
          'ca19',
          'tiroglobulina',
          'emo',
          'gram',
          'proteinuria',
          'microalbuminuria',
          'clearence',
          'TestEO',
          'coproparasitario',
          'coproparasitarioS',
          'sangre',
          'polimorfonucleares',
          'rotavirus',
          'oxiuros',
          'ph',
          'antígeno',
          'pylori',
          'muestra',
          'muestraE',
          'fresco',
          'gramm',
          'baar',
          'koh',
          'cultivoA',
          'cultivoH',
          'papanicolao',
          'eosinófilos',
          'espermograma',
          'cristalografia',
          'otros',
          'ottros'
         

    ];

    public $timestamps = false;
    
}


