<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Obtetra extends Model
{
    use HasFactory;
    protected $table = 'obtetra';

    protected $fillable = [

    
        'idObtetra',
        'q139_nacionalidad',
        'trip-start1',
        'q138_autoidentificacion138',
        'q42_sabeLeer',
        'q43_alfabetizacionE',
        'q45_viveSola',
        'q47_establecimientoDel',
        'q48_establecimientoDel48',
        'q14_name14',
        'q16_name16',
        'q17_name17',
        'q50_ultimoEmbarazo',
        'q51_embarazosMultiples',
        'q52_gestasPrevias',
        'q53_embMolar',
        'q54_embEctopico',
        'q55_abortos',
        'q56_partos',
        'q57_vaginales',
        'q58_cesareas',
        'q59_nacidosVivos',
        'q60_nacidosMuertos',
        'q61_viven',
        'q62_muertos1ra',
        'q63_despues1ra',
        'trip-start2',
        'q68_escribaUna',
        'q69_embarazoPlanificado',
        'q70_name70',
        'q74_pesoInicial',
        'q75_tallacm',
        'trip-start22',
        'trip-start3',
        'q78_name78',
        'q79_name79',
        'q80_fumaAct',
        'q80_fumaAct2',
        'q80_fumaAct3',
        'q81_fumaPas1',
        'q81_fumaPas2',
        'q81_fumaPas3',
        'q82_drogas1',
        'q82_drogas2',
        'q82_drogas3',
        'q83_alcohol1',
        'q83_alcohol2',
        'q83_alcohol3',
        'q84_violencia1',
        'q84_violencia2',
        'q84_violencia3',
         'q85_name85',
         'q86_antitetanicaVigente',
         'q88_1ra',
         'q89_2da',
         'q90_exNormal',
         'q90_exNormal2',
         'q91_cervix1',
         'q91_cervix2',
         'q91_cervix3',
         'q92_grupo',
         'q93_rh',
         'q94_inmuniz',
         'q95_name951',
         'q97_name972',
         'q98_tarvEn',
         'q99_gt2099',
         'q100_pruebaResutl',
         'q101_tarvEn101',
         'q103_escribaUna103',
         'q104_fefolatosIndicados',
         'q104_fefolatosIndicados2',
         'q105_hbgt20semGdl',

         'q106_escribaUna106',
         'q107_name107',
         'q108_name108',
         'q109_bacteriuriaSem',
          'q109_bacteriuriaSem2',
          'q110_glucemiaEn',
          'q110_glucemiaEn2',
          'q111_escribaUna111',
          'q112_prevencionPreeclampsia1',
          'q112_prevencionPreeclampsia2',
          'q112_prevencionPreeclampsia3',
          'q113_estreptococoB113',
          'q114_educacionPrenatalsesiones',
          'q115_planDe',
          'q116_consejeriaLactancia',
          'q118_pruebaNo',
          'q119_lt20',
          'q120_gt20',
          'q121_pruebaNo121',
          'q122_pruebaTreponemica',
          'q123_semanas',
          'q125_semanas125',
          'q124_pruebaTreponemica124',
          'q126_tratamiento',
          'q127_semanas127',
          'q128_semanas128',


          'q129_tratamiento129',
          'q130_ttoDe',
          'q131_ttoDe131',
          'trip-start55',
        //    'trip-start12',

        //    'a',
        //    'b',
        //    'c',
        //    'd',
        //    'f',
        //    'g',
        //    'h',
        //    'i',
        //    'j',
        //    'k',
        //    'l',
        //    'm',
        //    'n',
        //    'o',
        //    'p',
        //    'q',
        //   'qq',
        //    'trip-start65',
        //    'trip-start66',
 
        //    '2',


        //    '3',
        //    '4',
        //    '5',
        //    '6',
        //     '7',
        //     '8',
        //     '9',
        //     '10',
        //     '11',
        //     '12',
        //     '13',
        //     '14',
        //     '15',
        //     're',
        //     'er',
        //     '18',
        //     'trip-start67',
        //     'trip-start688',          
        //     'a1',
        //     'a2',
        //     'a3',
        //     'a4',
        //     'a5',
        //     'a6',
        //     'a7',
        //     'a8',
        //     'a9',        
        //    'a10',
        //    'a11',
        //    'a12',
        //    'a13',
        //     'a14',
        //     'a15',
        //     'a16',
        //     'a17',
        //     'trip-start68',
        //     'trip-start69',
        //     'b1',
        //     'b2',
        //     'b3',
        //     'b4',
        //     'b5',
        //     'b6',
        //     'b7',
        //     'b8',
        //     'b9',
        //     'b10',
        //     'b11',
        //     'b12',
        //     'b13',
        //     'b14',
        //     'b15',
        //     'b16',                    
        //    'b17',
        //    'trip-start70',
        //    'trip-start71',
        //    'c1',
        //     'c2',
        //     'c3',
        //     'c4',
        //     'c5',
        //     'c6',
        //     'c7',
        //     'c8',
        //     'c9',
        //     'c10',
        //     'c11',
        //     'c12',
        //     'c13',
        //     'c14',
        //     'c15',
        //     'c16',
        //     'c17',
        //     'trip-start73'
         

    ];

    public $timestamps = false;
}
